### ISSUE TITLE
Configure to consume data from HHS official JSON

### ISSUE THREAD

**Issue by daguar** [codeforamerica/fplapi#17]
If we set it up to consume from the JSON source here:
http://aspe.hhs.gov/dataset/2015-poverty-guidelines

then it may make the logic for updating be easier (we could set some date breakpoints, and after X date we look for `.../2016-poverty-guidelines` etc.

That said, it's a static data source, so this may not be super relevant given that it's a once-a-year change.

**Comment by mapsam** [comment]
Awesome, had no idea that this existed. Seems that the two options are:
1. Update manually once a year, set up a notification using EngineLight #18 
2. Consume the above JSON at some date (unknown date, but according to this website they updated theirs on January 22nd)

I'm leaning towards the one-time manual update, which is just a quick change to the JSON file, but flagging it a few days in advance and pulling in the changes at midnight (because we have a serious number of users right now).

Cool that they provide that JSON!

**Comment by daguar** [comment]
I agree with (1) being a good approach, and even better with EngineLight notifications, so let's close this one and put this elsewhere (partly in #18 )
